import { createCanvas, GlobalFonts, loadImage } from '@napi-rs/canvas';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { slugify } from '../src/slugify.js';

const ROOT = process.cwd();
const BASE_IMAGE_PATH = join(ROOT, 'assets/wotd/base.png');
const WORDS_PATH = join(ROOT, 'data/words.txt');
const FONT_PATH = join(ROOT, 'assets/fonts/Anton-Regular.ttf');
const OUTPUT_DIR = join(ROOT, 'public/wotd');
const PREVIEW_PATH = join(ROOT, 'assets/wotd/preview.png');
const WORDS_DATA_PATH = join(ROOT, 'src/data/wotd-words.ts');

const OUTPUT_WIDTH = 600;
const TOP_LINE_1 = 'DON CHEADLE';
const TOP_LINE_2 = 'WORD OF THE DAY';

function resolveFontFamily(): string {
  if (GlobalFonts.has('Impact')) {
    console.log('Using system Impact font.');
    return 'Impact';
  }
  GlobalFonts.registerFromPath(FONT_PATH, 'Anton');
  console.log('Impact not found; using bundled Anton font.');
  return 'Anton';
}

// Finds the largest font size (up to maxSize) whose text fits within maxWidth.
function fitFontSize(ctx: ReturnType<ReturnType<typeof createCanvas>['getContext']>, text: string, family: string, maxWidth: number, maxSize: number): number {
  let size = maxSize;
  while (size > 8) {
    ctx.font = `${size}px ${family}`;
    if (ctx.measureText(text).width <= maxWidth) return size;
    size -= 2;
  }
  return size;
}

function drawOutlinedText(
  ctx: ReturnType<ReturnType<typeof createCanvas>['getContext']>,
  text: string,
  x: number,
  y: number,
  fontSize: number,
) {
  ctx.lineWidth = Math.max(2, Math.round(fontSize / 10));
  ctx.strokeStyle = 'black';
  ctx.lineJoin = 'round';
  ctx.miterLimit = 2;
  ctx.strokeText(text, x, y);
  ctx.fillStyle = 'white';
  ctx.fillText(text, x, y);
}

async function renderWordImage(word: string, family: string, outputPath: string): Promise<void> {
  const base = await loadImage(BASE_IMAGE_PATH);
  const height = Math.round(base.height * (OUTPUT_WIDTH / base.width));
  const canvas = createCanvas(OUTPUT_WIDTH, height);
  const ctx = canvas.getContext('2d');

  ctx.drawImage(base, 0, 0, OUTPUT_WIDTH, height);
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  const margin = OUTPUT_WIDTH * 0.08;
  const maxWidth = OUTPUT_WIDTH - margin * 2;

  const topSize = Math.min(
    fitFontSize(ctx, TOP_LINE_1, family, maxWidth, OUTPUT_WIDTH * 0.14),
    fitFontSize(ctx, TOP_LINE_2, family, maxWidth, OUTPUT_WIDTH * 0.14),
  );
  ctx.font = `${topSize}px ${family}`;
  drawOutlinedText(ctx, TOP_LINE_1, OUTPUT_WIDTH / 2, height * 0.09 + topSize * 0.5, topSize);
  drawOutlinedText(ctx, TOP_LINE_2, OUTPUT_WIDTH / 2, height * 0.09 + topSize * 1.6, topSize);

  const bottomText = word.toUpperCase();
  const bottomSize = fitFontSize(ctx, bottomText, family, maxWidth, OUTPUT_WIDTH * 0.16);
  ctx.font = `${bottomSize}px ${family}`;
  drawOutlinedText(ctx, bottomText, OUTPUT_WIDTH / 2, height * 0.91 - bottomSize * 0.5, bottomSize);

  writeFileSync(outputPath, canvas.toBuffer('image/png'));
}

async function main() {
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  const previewIndex = args.indexOf('--preview');

  if (!existsSync(BASE_IMAGE_PATH)) {
    console.error(`Missing base image at ${BASE_IMAGE_PATH}. Add a clean photo there first.`);
    process.exit(1);
  }

  const family = resolveFontFamily();

  if (previewIndex !== -1) {
    const word = args[previewIndex + 1];
    if (!word) {
      console.error('Usage: --preview WORD');
      process.exit(1);
    }
    await renderWordImage(word, family, PREVIEW_PATH);
    console.log(`Wrote preview to ${PREVIEW_PATH}`);
    return;
  }

  if (!existsSync(WORDS_PATH)) {
    console.error(`Missing word list at ${WORDS_PATH}.`);
    process.exit(1);
  }

  const words = readFileSync(WORDS_PATH, 'utf-8')
    .split(/\r?\n/)
    .map((w) => w.trim())
    .filter(Boolean);

  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const word of words) {
    const slug = slugify(word);
    if (seen.has(slug)) duplicates.push(word);
    seen.add(slug);
  }
  if (duplicates.length > 0) {
    console.error(`Duplicate words in ${WORDS_PATH} (by slug): ${duplicates.join(', ')}`);
    process.exit(1);
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  let rendered = 0;
  let skipped = 0;
  for (const word of words) {
    const slug = slugify(word);
    const outputPath = join(OUTPUT_DIR, `${slug}.png`);
    if (existsSync(outputPath) && !force) {
      skipped++;
      continue;
    }
    await renderWordImage(word, family, outputPath);
    rendered++;
    console.log(`Rendered ${slug}.png`);
  }

  const dataLines = [
    '// Generated by `npm run render-wotd`. Do not edit by hand.',
    'export interface WotdWord {',
    '  word: string;',
    '  slug: string;',
    '}',
    '',
    'export const WOTD_WORDS: WotdWord[] = [',
    ...words.map((word) => `  { word: ${JSON.stringify(word)}, slug: ${JSON.stringify(slugify(word))} },`),
    '];',
    '',
  ];
  writeFileSync(WORDS_DATA_PATH, dataLines.join('\n'));

  console.log(`\nRendered ${rendered}, skipped ${skipped} (already existed), ${words.length} total words.`);
  console.log(`Wrote ${WORDS_DATA_PATH}`);
}

main();
